apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    database: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
    isDefault: true
    uid: postgres-ds

